{{- if and (not .Values.existingSecret) .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chorus.fullname" . }}-secret
  labels:
  {{- include "chorus.labels" . | nindent 4 }}
type: Opaque
data:
  config: {{ .Values.secret | b64enc | quote }}
{{- end -}}