port: 9673 # agent port to listen incoming notifications
url: "http://localhost:9673" # REQUIRED: url to be used by s3 storage to send notifications. The URL should be reachable for s3 storage.
fromStorage: "main" # REQUIRED: notifications source storage name from Chorus config

log:
  json: false # false for dev console logger, true - json log for prod to export to Grafana&Loki.
  level: info
metrics:
  enabled: false
  port: 9090
trace:
  enabled: false
  endpoint: # url to Jaeger or other open trace provider
redis:
  address: "redis:6379"
features:
  tagging: true # sync object/bucket tags
  acl: true # sync object/bucket ACLs
  lifecycle: false # sync bucket Lifecycle
  policy: false # sync bucket Policies

