storage:
  createRouting: true # create roting rules to route proxy requests to main storage
  createReplication: false # create replication rules to replicate data from main to other storages
  storages:
    main: # yaml key with some handy storage name
      address: "http://fake-s3-main:9000"
      credentials:
        user1:
          accessKeyID: fakeKey
          secretAccessKey: fakeSecret
      provider: Other # <Ceph|Minio|AWS|Other see providers list in rclone config> https://rclone.org/s3/#configuration
      isMain: true # <true|false> one of the storages in should be main
      healthCheckInterval: 10s
      httpTimeout: 1m
      isSecure: false #set false for http address
      rateLimit:
        enable: true
        rpm: 60
    follower: # yaml key with some handy storage name
      address: "http://fake-s3-follower:9000"
      credentials:
        user1:
          accessKeyID: fakeKey2
          secretAccessKey: fakeSecret2
      provider: Other
      isMain: false
      healthCheckInterval: 10s
      httpTimeout: 1m
      isSecure: false
      rateLimit:
        enable: true
        rpm: 60
